#Week 5 Lesson: Numpy

In [1]:
import numpy as np #NUMPY is a package that is built for numerical calculations (general functions that already exists in MATLAB) in python that we can call it by import order and can name it as whatever we want for calling it later.

##Numpy arrays

In [2]:
A1 = np.array([1,3,6,9])  #It receives a list as an input, and convert it into array.

In [3]:
A1

array([1, 3, 6, 9])

In [ ]:
L1 = [1,3,7,9]
A1 = np.array(L1)

In [ ]:
A1

array([1, 3, 7, 9])

The numpy arrays have SPECIFIC DATA TYPE. (different from list)

In [ ]:
A1.dtype

dtype('int64')

In [ ]:
L2 = [1.3,5.2,6.3,7.4]
A2 = np.array(L2)
A2.dtype

dtype('float64')

We can also define an array of integers

In [ ]:
L3 = ["Tomas", "Ramiro", "Luca", "Nima", "David"]

In [ ]:
A3 = np.array(L3)
A3.dtype

dtype('<U6')

In [ ]:
A3

array(['Tomas', 'Ramiro', 'Luca', 'Nima', 'David'], dtype='<U6')

What will happen if I define an array from a list that include items with different data types ?

In [ ]:
L4 = [2, "Tomas", 3.4]
A4 = np.array(L4)
A4

array(['2', 'Tomas', '3.4'], dtype='<U21')

In [ ]:
L5 = [2.3,5]
A5 = np.array(L5)
A5

array([2.3, 5. ])

In [ ]:
A5.dtype

dtype('float64')

So, it converts all the data types in the list, to a single type! (This is a limitation that array provides. Be careful.)

What is the use of using arrays !?
Let's start with lists and see the differences.

In [ ]:
L5 = [1.4,5.6,7.8]
L6 = [2.3,5.8,8.9]
L7 = L5 + L6
L7

[1.4, 5.6, 7.8, 2.3, 5.8, 8.9]

Adding lists together gives the cummulation of lists! But what if we want to act with lists like a vector for summation/substitution of the elements ! This is the point that arrays become useful.

In [ ]:
A5 = np.array(L5)
A6 = np.array(L6)
A7 = A5+A6

In [ ]:
A7

array([ 3.7, 11.4, 16.7])

So we can see that the vectorize operation occurs.

In [ ]:
A8 = A5 - A6
A8

array([-0.9, -0.2, -1.1])

In [ ]:
A9 = A5 * A6  #Element wise multiplication! not matrix multiplication.
A9

array([ 3.22, 32.48, 69.42])

**Matrix multiplication: how to do?**

In [ ]:
A10 = A5.dot(A6)
A10

105.12

In [ ]:
A11 = 2 * A5.dot(A9)
A11

1455.744

##How do we use it for our applications?

In [ ]:
opaque_item_list = ["wall","ceiling","door"]
opaque_item_array = np.array(opaque_item_list)
opaque_U_list = [0.438,0.25,1.78]
opaque_U_array = np.array(opaque_U_list)

In [ ]:
opaque_area_array = np.array([105.8, 200, 2.2])

In [ ]:
T_inside_building = 20
T_outside = -4.8
deltaT_heating = T_inside_building - T_outside

In [ ]:
opaque_HF_array = deltaT_heating*opaque_U_array
opaque_HF_array

array([10.8624,  6.2   , 44.144 ])

In [ ]:
opaque_Q_array = opaque_HF_array * opaque_area_array
opaque_Q_array

array([1149.24192, 1240.     ,   97.1168 ])

In [ ]:
opaque_Q_array_rounded = np.round(opaque_Q_array,2)
opaque_Q_array_rounded

array([1149.24, 1240.  ,   97.12])

Extracting data from arrays.

In [ ]:
Q_ceiling = opaque_Q_array_rounded[1]
Q_ceiling

1240.0

In [ ]:
Q_door = opaque_Q_array_rounded[-1]
Q_door

97.12

##Logical arrays

In [ ]:
theOneMoreThan1100 = opaque_Q_array_rounded > 1100  #Output would be bollean values.
theOneMoreThan1100

array([ True,  True, False])

Boolean operations: Python VS. Numpy!

Python:

In [ ]:
True and True

True

In [ ]:
True or False

True

In [ ]:
False and False

False

In [ ]:
not True

False

Numpy: (similar to MATLAB: &)

In [ ]:
theOneLessThan1200 = opaque_Q_array_rounded < 1200
theOneLessThan1200

array([ True, False,  True])

In [ ]:
theOneMoreThan1100LessThan1200 = theOneMoreThan1100 & theOneLessThan1200
theOneMoreThan1100LessThan1200

array([ True, False, False])

In [ ]:
theOneMoreThan1100LessThan1200 = np.logical_and(theOneMoreThan1100,theOneLessThan1200)
theOneMoreThan1100LessThan1200

array([ True, False, False])

##Boolean indexing: why do I need the boolean vectors?

In [ ]:
A12 = np.array([3,5,6,11])
A13 = A12 > 5
A13

array([False, False,  True,  True])

In [ ]:
A14 = A12[A13]
A14

array([ 6, 11])

##How can we use for our applications? (Boolean indexing)

In [ ]:
opaque_item_array

array(['wall', 'ceiling', 'door'], dtype='<U7')

In [ ]:
boolean_array_wall = opaque_item_array == "wall"
boolean_array_wall

array([ True, False, False])

In [ ]:
opaque_Q_array_rounded

array([1149.24, 1240.  ,   97.12])

In [ ]:
Q_wall = opaque_Q_array[boolean_array_wall]
Q_wall

array([1149.24192])

What to extracting the value?

In [ ]:
Q_wall = Q_wall[0]
Q_wall

1149.2419200000002

In [ ]:
Q_wall = opaque_Q_array[boolean_array_wall][0]
Q_wall

1149.2419200000002

Extracting an array of Q values aither for wall or ceiling

In [ ]:
boolean_array_wall_ceiling = (opaque_item_array == "wall") | (opaque_item_array == "ceiling")

In [ ]:
Q_wall_ceiling = opaque_Q_array_rounded[boolean_array_wall_ceiling]
Q_wall_ceiling

array([1149.24, 1240.  ])

##Sum and average in Numpy

In [ ]:
Q_tot_opaque = np.round(opaque_Q_array_rounded.sum())
Q_tot_opaque

2486.0

In [ ]:
Q_avg_opaque = np.around(opaque_Q_array_rounded.mean(),2)
Q_avg_opaque

828.79

##Using Numpy for our resistance problem

In [4]:
resistance_name = np.array(["R_internal", "R_foam", "R_wood", "R_plaster", "R_external"])
resistance_type = np.array(["conv", "cond", "cond", "cond", "conv"])
resistance_A = np.array([15,15,15,15,15])
resistance_k = np.array([None,0.05,0.4,1,None])
resistance_L = np.array([None, 0.06, 0.1, 0.01, None])
resistance_h = np.array([8.9, None, None, None, 20])

In [5]:
resistance_Rvalue = np.zeros(5)
resistance_Rvalue

array([0., 0., 0., 0., 0.])

To calculate the Rvalues:
First we create an array of booleans, that tells us which resistances are conductive

In [6]:
bool_resistance_cond = resistance_type == "cond"
bool_resistance_cond

array([False,  True,  True,  True, False])

In [7]:
resistance_L_cond = resistance_L[bool_resistance_cond]
resistance_L_cond

array([0.06, 0.1, 0.01], dtype=object)

In [8]:
resistance_k_cond = resistance_k[bool_resistance_cond]
resistance_k_cond

array([0.05, 0.4, 1], dtype=object)

In [9]:
resistance_A_cond = resistance_A[bool_resistance_cond]
resistance_A_cond

array([15, 15, 15])

In [10]:
resistance_R_cond = resistance_L_cond/resistance_k_cond/resistance_A_cond
resistance_R_cond

array([0.08, 0.016666666666666666, 0.0006666666666666666], dtype=object)

In [11]:
resistance_Rvalue[bool_resistance_cond] = resistance_R_cond

In [12]:
resistance_Rvalue

array([0.        , 0.08      , 0.01666667, 0.00066667, 0.        ])

In [13]:
bool_resistance_conv = resistance_type == "conv"
bool_resistance_conv

array([ True, False, False, False,  True])

In [14]:
resistance_A_conv = resistance_A[bool_resistance_conv]
resistance_A_conv

array([15, 15])

In [15]:
resistance_h_conv = resistance_h[bool_resistance_conv]
resistance_h_conv

array([8.9, 20], dtype=object)

In [16]:
resistance_Rvalue_conv = 1.0/resistance_h_conv/resistance_A_conv
resistance_Rvalue_conv

array([0.00749063670411985, 0.0033333333333333335], dtype=object)

In [17]:
resistance_Rvalue[bool_resistance_conv] = resistance_Rvalue_conv
resistance_Rvalue

array([0.00749064, 0.08      , 0.01666667, 0.00066667, 0.00333333])